const antiMeta = { svg: 'anti-meta', designer: 'TMD' }
const bandTogether = { svg: 'band-together', designer: 'Gabriel Vogel' }
const crimsonDoubleDown = { svg: 'crimson-double-down', designer: 'Ker\'is & Optimus Prime' }
const raidTiming = { svg: 'raid-timing', designer: 'Pixel Lab' }
const bullseye = { svg: 'bullseye', designer: 'Zlatko Najdenovski' }

const icons = {
  '20-20': { svg: 'twenty-twenty', designer: 'Chanut is Industries' },
  'abuse-of-power': { designer: 'naim' },
  'always-by-your-side': { designer: 'Simon Child' },
  'anti-meta': antiMeta,
  'automatic-lockdown': { designer: 'Jaime M. Laurel' },
  'avenge-cayde-6': { designer: 'farias' },
  'band-together': bandTogether,
  'bow-ness-points': { designer: 'Hat-Tech' },
  'boy-scout': { designer: 'AomAm' },
  bullseye,
  'chill-at-home': bandTogether,
  'clean-sweep': { designer: 'Rudez Studio' },
  'complete-the-cycle': { designer: 'Gregor Cresnar' },
  'crimson-double-down': crimsonDoubleDown,
  deathless: { designer: 'Robert Bjurshagen' },
  'double-down': { designer: 'Optimus Prime' },
  'doubles-double-down': crimsonDoubleDown,
  'feeling-blue': { designer: 'rivercon' },
  'flawless-striker': { designer: 'iconsphere' },
  'frag-and-tag': { designer: 'Hea Poh Lin, Krish & miza bin' },
  'guided-games-raid-timing': raidTiming,
  'hear-the-whisper': { designer: 'BGBOXXX Design' },
  'helping-hand': { designer: 'Demetria Rose' },
  'i-hit-a-rock': { designer: 'Tom Fricker' },
  'luke-skywalker-s-padawan': { designer: 'Colour Block' },
  'make-the-dreamwork': bandTogether,
  'my-motes-bring-all-the-boys-to-the-yard': { svg: 'all-creatures-great-small' },
  merciless: { designer: 'Optimus Prime' },
  'nice-throw': { designer: 'Hea Poh Lin' },
  'no-apologies': { designer: 'Simon Child' },
  'not-very-exotic': { designer: 'iconsphere' },
  perfection: { designer: 'Montu Yadav' },
  'pew-pew-pew': { designer: 'Nikol Kokešová' },
  'power-hungry': { designer: 'naim' },
  'raid-master': { designer: 'Robert Bjurshagen' },
  'raid-timing': raidTiming,
  'rocky-balboa-s-trainee': { designer: 'miza bin' },
  'stop-the-stopper': { designer: 'Optimus Prime' },
  'strike-death-penalty': { designer: 'Robert Bjurshagen' },
  'super-accurate': bullseye,
  'take-it-easy': { designer: 'Pixel Lab' },
  'telesto-festo': { designer: 'Casper Jensen' },
  'this-is-my-house': { designer: 'arif fajar yulianto' },
  'variety-is-the-spice-of-life': { designer: 'Xela Ub' },
  'warmind-anti-meta': antiMeta,
  'weapons-of-the-beasts': { designer: 'Lorc' },
  'winner-winner-chicken-dinner': { designer: 'Artem Kovyazin' },
  'wrong-game-mode': antiMeta,
  'you-can-t-kill-me': { designer: 'Robert Bjurshagen' },
  'you-ve-earned-it': { designer: 'Creative Stall' }
}

export default icons
