const icons = {
  '20_20': { svg: 'twenty-twenty', designer: 'Chanut is Industries' },
  AbuseOfPower: { svg: 'abuse-of-power', designer: 'naim' },
  AllCreaturesGreatSmall: { svg: 'all-creatures-great-and-small' },
  AlwaysByYourSide: { svg: 'always-by-your-side', designer: 'Simon Child' },
  AntiMeta: { svg: 'anti-meta', designer: 'TMD' },
  AnythingYouCanDo: { svg: 'anything-you-can-do' },
  AutomaticLockdown: { svg: 'automatic-lockdown', designer: 'Jaime M. Laurel' },
  AvengeCayde_6: { svg: 'avenge-cayde-6', designer: 'farias' },
  BandTogether: { svg: 'band-together', designer: 'Gabriel Vogel' },
  BeASuperhero: { svg: 'be-a-superhero' },
  BowNessPoints: { svg: 'bowness-points', designer: 'Hat-Tech' },
  BoyScout: { svg: 'boy-scout', designer: 'AomAm' },
  Bullseye: { svg: 'bullseye', designer: 'Zlatko Najdenovski' },
  ChillAtHome: { svg: 'band-together', designer: 'Gabriel Vogel' },
  CleanSweep: { svg: 'clean-sweep', designer: 'Rudez Studio' },
  CompleteTheCycle: { svg: 'complete-the-cycle', designer: 'Gregor Cresnar' },
  CrimsonDoubleDown: { svg: 'crimson-double-down', designer: 'Ker\'is & Optimus Prime' },
  Deathless: { svg: 'deathless', designer: 'Robert Bjurshagen' },
  DoubleDown: { svg: 'double-down', designer: 'Optimus Prime' },
  DoublesDoubleDown: { svg: 'crimson-double-down', designer: 'Ker\'is & Optimus Prime' },
  EfficiencyIsnTEverything: { svg: 'efficiency-isnt-everything' },
  FeelingBlue: { svg: 'feeling-blue', designer: 'rivercon' },
  FlawlessStriker: { svg: 'flawless-striker', designer: 'iconsphere' },
  FlyingTheFlag: { svg: 'flying-the-flag' },
  FragAndTag: { svg: 'frag-and-tag', designer: 'Hea Poh Lin, Krish & miza bin' },
  GuidedGamesRaidTiming: { svg: 'raid-timing', designer: 'Pixel Lab' },
  HearTheWhisper: { svg: 'hear-the-whisper', designer: 'BGBOXXX Design' },
  HelpingHand: { svg: 'helping-hand', designer: 'Demetria Rose' },
  IHitARock: { svg: 'i-hit-a-rock', designer: 'Tom Fricker' },
  LetMeHandleThis: { svg: 'let-me-handle-this' },
  LukeSkywalkerSPadawan: { svg: 'luke-skywalkers-padawan', designer: 'Colour Block' },
  MakingADeposit: { svg: 'making-a-deposit' },
  MakeTheDreamwork: { svg: 'band-together', designer: 'Gabriel Vogel' },
  MyMotesBringAllTheBoysToTheYard: { svg: 'all-creatures-great-and-small' },
  Merciless: { svg: 'merciless', designer: 'Optimus Prime' },
  NiceThrow: { svg: 'nice-throw', designer: 'Hea Poh Lin' },
  NoApologies: { svg: 'no-apologies', designer: 'Simon Child' },
  NotSoSuper: { svg: 'not-so-super' },
  NotVeryExotic: { svg: 'not-very-exotic', designer: 'iconsphere' },
  OhNoYouDonT: { svg: 'oh-no-you-dont' },
  OopsIMTrash: { svg: 'oops-im-trash' },
  Perfection: { svg: 'perfection', designer: 'Montu Yadav' },
  PewPewPew: { svg: 'pew-pew-pew', designer: 'Nikol Kokešová' },
  PowerHungry: { svg: 'power-hungry', designer: 'naim' },
  RaidMaster: { svg: 'raid-master', designer: 'Robert Bjurshagen' },
  RaidTiming: { svg: 'raid-timing', designer: 'Pixel Lab' },
  RockyBalboaSTrainee: { svg: 'rocky-balboas-trainee', designer: 'miza bin' },
  StopTheStopper: { svg: 'stop-the-stopper', designer: 'Optimus Prime' },
  StrikeDeathPenalty: { svg: 'strike-death-penalty', designer: 'Robert Bjurshagen' },
  Supers_2_0: { svg: 'supers-two-point-zero' },
  SuperAccurate: { svg: 'bullseye', designer: 'Zlatko Najdenovski' },
  TakeItEasy: { svg: 'take-it-easy', designer: 'Pixel Lab' },
  TelestoFesto: { svg: 'telesto-festo', designer: 'Casper Jensen' },
  ThisIsMyHouse: { svg: 'this-is-my-house', designer: 'arif fajar yulianto' },
  VarietyIsTheSpiceOfLife: { svg: 'variety-is-the-spice-of-life', designer: 'Xela Ub' },
  WarmindAntiMeta: { svg: 'anti-meta', designer: 'TMD' },
  WeaponsOfTheBeasts: { svg: 'weapons-of-the-beasts', designer: 'Lorc' },
  WinnerWinnerChickenDinner: { svg: 'winner-winner-chicken-dinner', designer: 'Artem Kovyazin' },
  WrongGameMode: { svg: 'anti-meta', designer: 'TMD' },
  YouCanTKillMe: { svg: 'you-cant-kill-me', designer: 'Robert Bjurshagen' },
  YouVeEarnedIt: { svg: 'youve-earned-it', designer: 'Creative Stall' },
  ZoneCaptured: { svg: 'zone-captured' }
}

export default icons
